version: '3.1'
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'gmac_authorization'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'pass_word'
      MYSQL_USER: 'admin'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql:/var/lib/mysql