version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: SWkIwZ73n1
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/data/postgres